# **Решение задач в Numpy**

# Создание массивов

Создать вектор со значениями 1, 5, 2, 7, 4.

In [ ]:
import numpy as np
a = np.array([1, 5, 2, 7, 4])
print(a)

[1 5 2 7 4]


Создать вектор со значениями от 10 до 49 включительно.

In [ ]:
#b = np.array([i for i in range(10, 50)])
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Создать вектор размера 10, заполненный числом 2,5.

In [ ]:
c = np.full(10, 2.5)
print(c)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненый нулями.


In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор из 30-ти случайных значений.

In [ ]:
b = np.empty(30)
#c = np.random.rand(30)
print(b)

[6.67797585e-310 4.78350319e-310 1.94209461e+227 1.94533523e+227
 2.43208811e-152 1.99803517e+161 6.01346953e-154 4.61912988e+281
 2.11651649e+214 3.55946858e+180 2.58415091e+161 1.36723614e+161
 2.20892684e+161 5.36835912e+252 3.99461109e+252 1.38519249e+219
 1.48973054e+214 6.01334504e-154 4.67261572e+164 2.21705231e+068
 6.01346953e-154 1.67501583e+243 2.57686994e+161 1.06842965e-258
 2.87242302e-027 6.01334666e-154 3.68067497e+180 2.46345036e-154
 2.65141253e+180 3.99461109e+252]


Создать матрицу 2х3: первая строка - 1, 2, 3, вторая строка - 7, 4, 5.

In [ ]:
c = np.array([[1, 2, 3],
             [7, 4, 5,]])
print(c)

[[1 2 3]
 [7 4 5]]


Создать матрицу размера 3x3, преобразовав вектор со значениями от 0 до 8.

In [ ]:
a = np.arange(9)
b = a.reshape(3, 3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Создать матрицу размером 4x2 со случайными вещественными значениями.

In [ ]:
a = np.random.rand(4, 2)
print(a)

[[0.08362628 0.9145967 ]
 [0.39365198 0.22752867]
 [0.86106197 0.82638669]
 [0.30123562 0.92917775]]


Создать матрицу 2х3 с целыми числами в диапазоне от 1 до 10.

In [ ]:
a = np.random.randint(1, 11, (2, 3))
print(a)

[[9 7 7]
 [3 9 6]]


Создать матрицу 2 х 3 и заполнить ее цифрой семь.

In [ ]:
a = np.full((2, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]]


Создать единичную матрицу 4х4.

In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Индексирование массивов

1. Создать вектор со значениями от 0 до 10.
2. Вывести 1-й элемент массива.
3. Вывести последний элемент массива.
4. Вывести элементы массива с 3 по 7.
5. Вывести первые 4 элемента массива.
6. Вывести последние 3 элемента массива.
7. Вывести элементы массива в обратном порядке.
8. Вывести элементы массива с индексами 0, 1, 7.

In [ ]:
a = np.arange(11)
print(a)
print(a[0])
print(a[-1])
print(a[3:8])
print(a[:4])
print(a[7:])
print(a[::-1])
print(a[[0, 1, 7]])

[ 0  1  2  3  4  5  6  7  8  9 10]
0
10
[3 4 5 6 7]
[0 1 2 3]
[ 7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]
[0 1 7]


1. Создать матрицу размера 3x3 со значениями от 0 до 8.
2. Вывести вторую строку матрицы.
3. Вывести третий столбец матрицы.
4. Вывести второй и третий элементы второй строки матрицы.
5. Вывести первый и второй элементы третьего столбца матрицы.
6. Вывести элемент матрицы, равный 0.

In [ ]:
b = np.arange(9)
a = b.reshape(3, 3)
print(a)
print(a[1])
print(a[:, 2])
print(a[1, 1:])
print(a[:2, 2])
print(a[a==0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
[2 5 8]
[4 5]
[2 5]
[0]


# Арифметические операции над массивами

1. Создать вектор со значениями от 0 до 5.
2. Прибавить к элементам вектора 2.
3. Умножить элементы вектора на 7.
4. Разделить элементы вектора на 4.
5. Возвести элементы вектора в 3-ю степень.

In [ ]:
a = np.arange(6)
print(a)
a += 2
print(a)
a *= 7
print(a)
a //= 4
print(a)
a **= 3
print(a)

[0 1 2 3 4 5]
[2 3 4 5 6 7]
[14 21 28 35 42 49]
[ 3  5  7  8 10 12]
[  27  125  343  512 1000 1728]


1. Создать 2 вектора со значениями от 0 до 5.
2. Реализовать поэлементное сложение векторов.
3. Реализовать поэлементное умножение векторов.
4. Реализовать поэлементное деление векторов.

In [ ]:
a = np.arange(6)
b = np.arange(6)
print(a)
print(b)
res = a + b
print(res)
res = a * b
print(res)
res = a // b
print(res)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]
[0 1 1 1 1 1]


<ipython-input-61-bfdfb613374f>:9: RuntimeWarning: divide by zero encountered in floor_divide
  res = a // b


1. Создать две матрицы 2х3 из векторов со значениями от 0 до 5.
2. Реализовать поэлементное сложение матриц.
3. Реализовать поэлементное умножение матриц.
4. Реализовать поэлементное деление матриц.

In [ ]:
a = np.arange(6)
b = a.reshape(2, 3)
c = np.arange(6)
d = c.reshape(2, 3)
print(b)
print(d)
print()
print(b + d)
print()
print(b * d)
print()
print(b // d)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]

[[ 0  2  4]
 [ 6  8 10]]

[[ 0  1  4]
 [ 9 16 25]]

[[0 1 1]
 [1 1 1]]


<ipython-input-60-18e006aa8b54>:12: RuntimeWarning: divide by zero encountered in floor_divide
  print(b // d)


# Логические операции над массивами

Создать матрицу размера 3x3 из векторов со значениями от 0 до 8.
1. Вывести элементы матрицы, значения которых больше или равны 5.
2. Вывести элементы матрицы, значения которых меньше 2 и больше 7.
3. Вывести элементы матрицы, значения которых лежат в диапазоне [3; 6).

In [ ]:
a = np.arange(9)
b = a.reshape(3, 3)

print(b[b>=5])
print(b[(b<2)| (b>7)])
print(b[(b>=3) & (b<6)])

[5 6 7 8]
[0 1 8]
[3 4 5]


# Операции с массивами

## Изменение формы массива

Создать произвольную матрицу матрицу размера 3x4 и преобразовать ее в одномерный массив.

In [ ]:
a = np.random.rand(3, 4)
b = a.flatten()
print(b)

[0.24469346 0.61754318 0.98516339 0.84858266 0.83946715 0.12392351
 0.56946479 0.57043413 0.33290833 0.70870634 0.71032249 0.01451477]


Создать вектор из 12 элементов и преобразовать его в матрицу:
- 3 х 4;
- 2 х 6;
- 5 х 3.

In [ ]:
a = np.arange(1, 13)
print(a)
print()
b = a.reshape(3, 4)
print(b)
print()
c = a.reshape(2, 6)
print(c)
d = a.reshape(5, 4) #Ошибка

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ValueError: cannot reshape array of size 12 into shape (5,4)

Создать вектор из 12 элементов и преобразовать его в массив размерностью 1 х 12.

In [ ]:
a = np.arange(1, 13)
a.reshape(1, 12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Замена элементов массивов

Создать вектор со значениями 1, 5, 2, 7, 4 и изменить 2-й элемент на 9.

In [ ]:
a = np.array([1, 5, 2, 7, 4])
print(a)
a[1] = 9
a

[1 5 2 7 4]


array([1, 9, 2, 7, 4])

Создать вектор с 10-ю случайными значениям и заменить максимальный элемент на ноль.


In [ ]:
a = np.random.rand(10)
print(a)
max_index = np.argmax(a)
a[max_index] = 0
print(a)

[0.17221806 0.42109152 0.95116063 0.14707495 0.04440606 0.0318366
 0.05632467 0.57175841 0.77027538 0.46431886]
[0.17221806 0.42109152 0.         0.14707495 0.04440606 0.0318366
 0.05632467 0.57175841 0.77027538 0.46431886]


Создать вектор со значениями [4, 5, 5, 7, 8, 8, 9, 12].
1. Заменить все элементы, равные 8 на 17.
2. Заменить все элементы, меньше 5 на 15.
3. Заменить все элементы, больше 5 и меньше или равные 7 на 30.

In [ ]:
a = np.array([4, 5, 5, 7, 8, 8, 9, 12])
a[a==8] = 17
a

array([ 4,  5,  5,  7, 17, 17,  9, 12])

Создать матрицу 2х3 и заполнить ее целыми случайными значениями в диапазоне от 0 до 10. Заменить элемент с индексом (2, 1) на значение 100.

In [ ]:
a = np.random.randint(0, 10, (2, 3))
print(a)
a[2][1] = 100
print(a)

[[5 2 6]
 [4 4 8]]


IndexError: index 2 is out of bounds for axis 0 with size 2

## Сортировка массивов

Создать вектор и отсортировать его элементы по убыванию и возрастанию значений.

In [ ]:
a = np.array([3, 4, 9, 3, 0, 203, 23, -2])
print(np.sort(a))
print(np.sort(a)[::-1])

[ -2   0   3   3   4   9  23 203]
[203  23   9   4   3   3   0  -2]



Создать матрицу 4х6 и заполнить ее случайными целыми значениями в диапазоне от 0 до 10. Отсортировать созданную матрицу по возрастанию по строкам и столбцам.

In [ ]:
a = np.random.randint(0, 11, (4, 6))
print(a)
print(np.sort(a)) # Сортировка по строкам
print(np.sort(a, axis=0)) # Сортировка по столбцам

[[ 0  8  7 10  6  8]
 [ 3  9  0  1  5  2]
 [ 1  3  3  7  3  6]
 [10  9  2  4  2  5]]
[[ 0  6  7  8  8 10]
 [ 0  1  2  3  5  9]
 [ 1  3  3  3  6  7]
 [ 2  2  4  5  9 10]]
[[ 0  3  0  1  2  2]
 [ 1  8  2  4  3  5]
 [ 3  9  3  7  5  6]
 [10  9  7 10  6  8]]


Создать матрицу 5х5 со случайными элементами и отсортировать ее по 3-му столбцу.


In [ ]:
a = np.random.randint(0, 11, (5, 5))
print(a)
b = np.argsort(a[:, 2])
a = a[b]
print(a)

[[ 0  4  5  8  4]
 [ 6  7 10  7  3]
 [ 1  4  8  6  6]
 [ 9  2 10  7  3]
 [ 6  4  6  9  4]]
[[ 0  4  5  8  4]
 [ 6  4  6  9  4]
 [ 1  4  8  6  6]
 [ 6  7 10  7  3]
 [ 9  2 10  7  3]]


## Объединение и разделение массивов, добавление элементов

Создать вектор с элементами от 1 до 7.
1. Добавить в конец значение 8.
2. Добавить в конец массив 9, 10, 11.

In [ ]:
a = np.arange(1, 8)
print(a)
b = np.append(a, 8)
print(b)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8]


Создать 2 вектора `[1, 2, 3, 4]` и `[5, 6, 7, 8]`.

1. Объединить вектора в один вектор.
2. Объединить вектора в матрицу 2х4.
3. Объединить вектора в матрицу 4х2.

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
#print(np.concatenate([a, b]))
print(np.hstack([a, b]))
print(np.hstack([a, b]).reshape((2,4)))
#print(np.vstack([a, b]).reshape((4,2)))
print(np.column_stack([a,b]))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


Создать 2 матрицы 2х2: первая содержит элементы от 1 до 4, вторая от 5 до 8.

1. Сформировать матрицу 2х4.
2. Сформировать матрицу 4х2.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.hstack([a, b]))
print(np.vstack([a, b]))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Создать вектор `[1, 2, 2, 3, 5, 6, 7, 10]`.
1. Добавить в конец массива число 12.
2. Вставить число 9 между числами 7 и 10.

In [ ]:
a = np.array([1, 2, 2, 3, 5, 6, 7, 10])
a = np.append(a, 12)
print(a)
a = np.insert(a, 7, 9)
print(a)

[ 1  2  2  3  5  6  7 10 12]
[ 1  2  2  3  5  6  7  9 10 12]


Создать произвольную матрицу и добавить строку.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])
a = np.vstack([a, b])
print(a)
#a = np.insert(a, 2, b, axis=0)
#print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Создать произвольную матрицу и добавить столбец.

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8])
#a = np.hstack([a, b[:, np.newaxis]])
#print(a)
a = np.insert(a, 3, b, axis=1)
print(a)

[[1 2 3 7]
 [4 5 6 8]]


Создать произвольную матрицу размера 3х4.
1. Вставить столбец между 1-м и 2-м столбцами.
2. Вставить строку между 2-й и 3-й строками.

In [12]:
a = np.array([[1, 2, 3, 4], [ 5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([0, 0, 0])
print(np.insert(a, 1, b, axis=1))
print(np.insert(a, 2, b, axis=1))

[[ 1  0  2  3  4]
 [ 5  0  6  7  8]
 [ 9  0 10 11 12]]
[[ 1  2  0  3  4]
 [ 5  6  0  7  8]
 [ 9 10  0 11 12]]


Создать вектор со значениями от 1 до 8. Разделить вектор на два вектора.

In [13]:
a = np.arange(1, 9)
print(np.split(a, 2))

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


Создать матрицу 4х4 со значениями от 1 до 17.
1. Разделить ее на 2 матрицы размером 4х2.
2. Разделить ее на 2 матрицы размером 2х4.

In [30]:
a = np.arange(1, 17).reshape(4, 4)
b1 = a[:, :2]
b2 = a[:, 2:]
print(b1)
print(b2)
c1 = a[:2, :]
c2 = a[2:, :]
print(c1)
print(c2)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


# Математические функции для работы с массивами

Создать матрицу 3х4 из элементов `[7, 1, 7, 8, 4, 2, 4, 5, 3, 5, 2, 3]`.
1. Найти минимальный и максимальный элементы матрицы.
2. Найти индексы минимального и максимального элементов матрицы.
3. Найти сумму всех элементов матрицы.
4. Найти среднее арифметическое всех элементов матрицы.

In [37]:
a = np.array([7, 1, 7, 8, 4, 2, 4, 5, 3, 5, 2, 3]).reshape(3,4)
print(a)
print(np.argmin(a), np.argmax(a))
print(np.sum(a))
print(np.mean(a))

[[7 1 7 8]
 [4 2 4 5]
 [3 5 2 3]]
1 3
51
4.25


Найти в каждой строке и каждом столбце:
- минимальные и максимальные элементы;
- суммы элементов и их среднее арифметическое.

In [40]:
print(np.min(a, axis=1), np.max(a, axis=1)) # Строки
print(np.min(a, axis=0), np.max(a, axis=0)) # Столбцы
print(np.sum(a, axis=1), np.mean(a, axis=1)) # Строки
print(np.sum(a, axis=0), np.mean(a, axis=0)) # Столбцы

[1 2 2] [8 5 5]
[3 1 2 3] [7 5 7 8]
[23 15 13] [5.75 3.75 3.25]
[14  8 13 16] [4.66666667 2.66666667 4.33333333 5.33333333]


# Элементы линейной алгебры

Создать произвольные вектора и найти их скалярное произведение.

In [42]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
print(np.dot(a,b))

130


Создать произвольную матрицу и вектор и найти их скалярное произведение.

In [45]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],
             [7, 8, 9],
             [10, 11, 12]])
print(np.dot(b, a))

[32 50 68]


Создать произвольные матрицы и найти их скалярное произведение.

In [47]:
a = np.arange(1, 17).reshape(4, 4)
b = np.arange(18, 34).reshape(4, 4)
print(np.dot(a,b))

[[ 260  270  280  290]
 [ 644  670  696  722]
 [1028 1070 1112 1154]
 [1412 1470 1528 1586]]


Найти корни уравнения вида $5 \cdot x^2 + 2 \cdot x = 3$

In [48]:
a = [5, 2, -3]
print(np.roots(a))


[-1.   0.6]


Решить систему уравнений

\begin{matrix}
2 \cdot x_1 + 5 \cdot x_2 = 1
\\ x_1 - 10 \cdot x_2 = 3
\end{matrix}

In [53]:
a = np.array([[2, 5],
              [1, -10]])
b = np.array([1, 3])
print(np.linalg.inv(a).dot(b))
print(np.linalg.solve(a, b))

[ 1.  -0.2]
[ 1.  -0.2]


Решить систему уравнений

\begin{matrix}
x_1 + x_3 = 2
\\
-x_1 + x_2 - 2 \cdot x_3 + x_4 = -2
\\
4 \cdot x_1 + x_3 - 2 \cdot x_4 = 0
\\
-4 \cdot x_1 + 4 \cdot x_2 + x_4 = 5
\end{matrix}


In [55]:
a = np.array([[1, 0, 1, 0],
             [-1, 1, -2, 1],
             [4, 0, 1, -2],
             [-4, 4, 0, 1]])
b = np.array([2, -2, 0, 5])
print(np.linalg.solve(a, b))
print(np.linalg.inv(a).dot(b))

[0. 1. 2. 1.]
[0. 1. 2. 1.]
